exclude: [ Archive, scripts, "Gemfile*", "*.ipynb", ".github", ".vscode" ]
markdown: GFM
repository: tustin2121/James_Somerton_Transcripts
defaults:
  -
    scope:
      path: "_videos"
    values:
      layout: "transcript"
      status: Missing
      podcast:
        comment-author: "Tustin2121"
        comment: "Note: there tends to be a lot of cross-talk in these podcasts. I'll attempt to fill in where possible, but I make no promises. There's a reason I didn't listen to these podcast episodes in the first place..."
plugins:
  # - jemoji
  - jekyll-redirect-from
whitelist:
  - jekyll-redirect-from
readme_index:
  enabled: true
collections:
  videos:
    output: true
    permalink: /:collection/:title
    layout: transcript
  themes:
    output: true
    permalink: /:collection/:title
    layout: default
